import { DefaultTheme } from 'styled-components';

export const lightTheme: DefaultTheme = {
  palette: {
    primary: {
      main: '#fdd835',
      light: '#ffff6b',
      dark: '#c6a700',
      contrastText: '#000000',
    },
    secondary: {
      main: '#212121',
      light: '#484848',
      dark: '#000000',
      contrastText: '#FFFFFF',
    },
    error: {
      main: '#D62300',
      light: '#FCEDEB',
      dark: '#9b1900',
      contrastText: '#000000',
    },
    warning: {
      main: '#FFAA00',
      light: '#ffde9d',
      dark: '#9d6900',
      contrastText: '#000000',
    },
    success: {
      main: '#198737',
      light: '#EDF5ED',
      dark: '#0d451c',
      contrastText: '#000000',
    },
    text: { primary: '#000000', secondary: '#ffffff', disabled: '#000000' },
    background: { primary: '#FFFFFF', secondary: '#f5f5f5' },
    border: '#e0e0e0',
  },
  breakpoints: {
    xs: 0,
    sm: 600,
    md: 900,
    lg: 1200,
    xl: 1536,
  },
  typography: {
    h1: {
      fontFamily: 'Roboto, sans-serif',
      fontWeight: 300,
      fontSize: '96px',
      lineHeight: '112px',
      color: 'rgba(0,0,0,0.87)',
      letterSpacing: '-1.5px',
    },
    h2: {
      fontFamily: 'Roboto, sans-serif',
      fontWeight: 300,
      fontSize: '60px',
      lineHeight: '72px',
      color: 'rgba(0,0,0,0.87)',
      letterSpacing: '-0.5px',
    },
    h3: {
      fontFamily: 'Roboto, sans-serif',
      fontWeight: 'normal',
      fontSize: '48px',
      lineHeight: '56px',
      color: 'rgba(0,0,0,0.87)',
    },
    h4: {
      fontFamily: 'Roboto, sans-serif',
      fontWeight: 'normal',
      fontSize: '34px',
      lineHeight: '36px',
      color: 'rgba(0,0,0,0.87)',
      letterSpacing: '0.25px',
    },
    h5: {
      fontFamily: 'Roboto, sans-serif',
      fontWeight: 400,
      fontSize: '28px',
      lineHeight: '32px',
      letterSpacing: '0.18px',
      color: 'rgba(0,0,0,0.87)',
    },
    h6: {
      fontFamily: 'Roboto, sans-serif',
      fontWeight: 500,
      fontSize: '24px',
      lineHeight: '28px',
      color: 'rgba(0,0,0,0.87)',
      letterSpacing: '0.15px',
    },
    body1: {
      fontFamily: 'Roboto, sans-serif',
      fontWeight: 'normal',
      fontSize: '20px',
      lineHeight: '28px',
      color: 'rgba(0,0,0,0.87)',
      letterSpacing: '0.5px',
    },
    body2: {
      fontFamily: 'Roboto, sans-serif',
      fontWeight: 400,
      fontSize: '16px',
      lineHeight: '20px',
      color: 'rgba(0,0,0,0.87)',
      letterSpacing: '0.25px',
    },
    subtitle1: {
      fontFamily: 'Roboto, sans-serif',
      fontWeight: 'normal',
      fontSize: '20px',
      lineHeight: '24px',
      color: 'rgba(0,0,0,0.87)',
      letterSpacing: '0.15px',
    },
    subtitle2: {
      fontFamily: 'Roboto, sans-serif',
      fontWeight: 500,
      fontSize: '18px',
      lineHeight: '20px',
      color: 'rgba(0,0,0,0.87)',
      letterSpacing: '0.1px',
    },
    button: {
      fontFamily: 'Roboto, sans-serif',
      fontWeight: 500,
      fontSize: '18px',
      lineHeight: '20px',
      color: 'rgba(0,0,0,0.87)',
      letterSpacing: '1.25px',
    },
    caption: {
      fontFamily: 'Roboto, sans-serif',
      fontWeight: 'normal',
      fontSize: '16px',
      lineHeight: '18px',
      color: 'rgba(0,0,0,0.87)',
      letterSpacing: '0.4px',
    },
    overline: {
      fontFamily: 'Roboto, sans-serif',
      fontWeight: 500,
      fontSize: '14px',
      lineHeight: '16px',
      color: 'rgba(0,0,0,0.87)',
      textTransform: 'initial',
      letterSpacing: '1.5px',
    },
  },
};
